### ISSUE TITLE
TODO: Rewriting the Combat System

### ISSUE THREAD

**Issue by chaendizzle** [chaendizzle/The-Amazing-RPG#9]
TODO:
 - [] game functions
     - [] death
     - [] combat entrance animation
     - [] evade animation
     - [] entity swapping
     - [] basic combat end recognition
 - [] combat GUI
     - [] action buttons
         - [] attack
         - [] defend
         - [] switch
         - [] swap
         - [] wait
         - [] flee
         - [] skill
         - [] item
         - [] equip
 - [] buffs and status effects
     - [] buffs for all stats
     - [] modify combat entity stat getters
     - [] status effects
         - [] stun
         - [] death
     - [] status buffs
         - [] flee
         - [] revive
     - [] buff/status effect/status buff "combat modifier" display system     - [] 
 - [] more drawing stuff like combat info drawing
     - [] drawEntityInfo
     - [] drawAdvancedEntityInfo
     - [] drawActionInfo
 - [] counterattacking
     - [] queueing
     - [] executing in the task system
 - [] skills and abilities -> combat actions
     - [] arctic blast
     - [] pepe blast
     - [] kill
     - [] scan
     - [] heal
     - [] melee attack
     - [] laser attack
     - [] pardon me!? laser attack
     - [] laser sweep
     - [] laser burst
     - [] scythe rain
     - [] knife throw
     - [] unleash
     - [] quick slash
     - [] revive
 - [] Debug
     - [] remove all dependencies to obj_combatController.
     - [] change room ordering to put the real game back in.
 - [] combat loading
     - [] enemy wave system
     - [] player backup system
     - [] map enemies -> entering combat
     - [] combat loading functions
 - [] the sigmoid exp system and leveling up
     - [] damage and healing increases XP multiplier for the character
     - [] increase XP to level up
     - [] leveling up increases stats
 - [] combat end and rewards
     - [] add to gold, AP, and XP, level up if necessary
 - [] enemy AI
     - [] skill chain branch system
 - [] WinMerge
